# Advent of code 2020

## day 1

https://adventofcode.com/2020/day/1

part 1

In [2]:
import numpy as np

In [5]:
data = np.loadtxt('input_01.txt',dtype = 'i')

In [6]:
data[0]

1227

In [15]:
XX,YY = np.meshgrid(data,data)
ZZ = XX+YY

In [18]:
ind = np.where(ZZ == 2020)[0]

In [19]:
answer = data[ind[0]]*data[ind[1]]
print[answer]

1010884

part 2

In [21]:
XX,YY,WW = np.meshgrid(data,data,data)
ZZ = XX+YY+WW

In [26]:
np.where(ZZ == 2020)

(array([55, 55, 78, 78, 88, 88]),
 array([78, 88, 55, 88, 55, 78]),
 array([88, 78, 88, 55, 78, 55]))

In [27]:
ind= [55,78,88]

In [30]:
answer = data[ind[0]]*data[ind[1]]*data[ind[2]]

In [31]:
print(answer)

253928438


# day 2

https://adventofcode.com/2020/day/2

In [8]:
import numpy as np
import pandas as pd
import re

In [6]:
data = pd.read_csv('input_02.txt',sep=' |:|-',names = ['n_min','n_max','letter','unused','password'])

<ipython-input-6-d139f05257f6>:1: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  data = pd.read_csv('input_02.txt',sep=' |:|-',names = ['n_min','n_max','letter','unused','password'])


In [79]:
data.drop('unused',axis = 1,inplace=True)
# data.drop('pw_valid',axis = 1,inplace=True)

In [80]:
def check_pw_1(n_min,n_max,letter,password):
    p = re.compile(letter)
    n = p.findall(password)
    return (len(n)>=n_min)&(len(n)<=n_max)

In [81]:
data['pw_valid_1'] = False

In [82]:
for k in data.index:
    data.loc[k,'pw_valid_1']= check_pw_1(data.n_min[k],data.n_max[k],data.letter[k],data.password[k])

In [83]:
data.sample(5)

n_min  n_max letter              password  pw_valid_1
963     10     12      t       tttqxrtttttvjrc       False
101      5      9      p  kppppcppnqpppqpzpppw       False
919     12     14      d        kvbwfkjzdcpcjd       False
436      2      3      x                  xmxz        True
72       5     10      p          ppgfpzczphpp        True

In [85]:
answer = data.pw_valid_1.sum()
print(answer)

474


part 2

In [138]:
data['pw_valid_2'] = False

In [144]:
def check_pw_2(n_min,n_max,letter,password):
#     p = re.compile('.{%i}'%(n_min-1)+letter+'.{%i}'%(n_max-n_min-1)+'[^%s]'%(letter))
    p_1 = re.compile('.{%i}%s'%(n_min-1,letter))
    p_2 = re.compile('.{%i}%s'%(n_max-1,letter))
    n_1 = p_1.match(password)
    n_2 = p_2.match(password)
    return bool(n_1)^bool(n_2)

In [145]:
for k in data.index:
    data.loc[k,'pw_valid_2']= check_pw_2(data.n_min[k],data.n_max[k],data.letter[k],data.password[k])

In [146]:
data.sample(5)

n_min  n_max letter              password  pw_valid_1  pw_valid_2
960      1      4      v                vfvvvc        True       False
534      6      7      z         pfnzzzzzwjzxg        True       False
4        7      8      k              rkkkknkw       False        True
784      9     20      g  ggggghgggggcggggglgq        True        True
651      4      5      c               rzccmcc        True        True

In [147]:
answer_2 = data.pw_valid_2.sum()
print(answer_2)

745


## day 3

https://adventofcode.com/2020/day/3

In [1]:
import numpy as np


In [6]:
text_file = open('input_03.txt','r')

In [7]:
data = text_file.read()

In [10]:
data = data.split('\n')

In [22]:
periodicity = len(data[0])
right = [3]
down = [1]

In [31]:
n_trees = 0
k = 0
while k < (len(data)-1):
    n_trees += data[k*down[0]][(right[0]*k)%periodicity] == '#'
    k+=1

print(n_trees)    


164


part 2

In [32]:
periodicity = len(data[0])
right = [1,3,5,7,1]
down = [1,1,1,1,2]


In [38]:
n_trees = np.zeros_like(right)
for n in range(len(right)):
    k = 0
    while k*down[n] < (len(data)-1):
        n_trees[n] += data[k*down[n]][(right[n]*k)%periodicity] == '#'
        k+=1

print(n_trees)    


[ 93 164  82  91  44]


In [40]:
answer = n_trees.prod()
print(answer)

5007658656


## day 4

https://adventofcode.com/2020/day/4

In [1]:
import numpy as np

In [41]:
text_file = open('input_04.txt','r')

data = text_file.read()


In [42]:
passports = data.split('\n\n')

In [4]:
passports[0]

'iyr:2015 cid:189 ecl:oth byr:1947 hcl:#6c4ab1 eyr:2026\nhgt:174cm\npid:526744288'

In [5]:
fields_2_check = ['byr','iyr','eyr','hgt','hcl','ecl','pid'] # cid optional

In [13]:
n_valid = 0

for pp in passports:
    valid = True
    for field in fields_2_check:
        valid = valid & (field+':' in pp)
    n_valid += valid
print(n_valid)

264


part 2

In [57]:
import re

In [188]:
passport_dicts = []
for pp in passports:
    pp_r = pp.replace('\n',' ')
    pp_r_s = pp.split()
    
    value_pairs = []
    for s in pp_r_s:
        value_pairs.append(s.split(':'))
    passport_dicts.append(dict(value_pairs))

In [194]:
passport_dicts[2]


{'ecl': 'oth',
 'hcl': '#733820',
 'cid': '124',
 'pid': '111220591',
 'iyr': '2019',
 'eyr': '2001',
 'byr': '1933',
 'hgt': '159in'}

In [220]:
def check_byr(ppd):
    key = 'byr'
    
    if key not in ppd.keys():
        return False
    else:     
        
        p = re.compile('^\d{4}$')
        n = p.match(ppd[key])

        if bool(n):
            x = int(ppd[key])
            return (x >= 1920) & (x <= 2002)
        else:
            return False

def check_iyr(ppd):
    key = 'iyr'
    
    if key not in ppd.keys():
        return False
    else:     
        
        p = re.compile('^\d{4}$')
        n = p.match(ppd[key])
       
        if bool(n):
            x = int(ppd[key])
            return (x >= 2010) & (x <= 2020)
        else:
            return False
        

def check_eyr(ppd):
    key = 'eyr'
    
    if key not in ppd.keys():
        return False
    else:     
        
        p = re.compile('^\d{4}$')
        n = p.match(ppd[key])
    
        if bool(n):
            x = int(ppd[key])
            return (x >= 2020) & (x <= 2030)
        else:
            return False
        
def check_hgt(ppd):
    key = 'hgt'
    
    if key not in ppd.keys():
        return False
    else: 
        
        p = re.compile('\d*((cm)|(in))')
        p2 = re.compile('\d*')
        n = p.match(ppd[key])
        n2 = p2.match(ppd[key])

        if bool(n):
            x = int(n2.group())
            if 'cm' in n.group():
                return (x >= 150) & (x <= 193)
            else:
                return (x >= 59) & (x <= 76)
        else:
            return False
        
def check_hcl(ppd):
    key = 'hcl'
    
    if key not in ppd.keys():
        return False
    else: 
        
        p = re.compile('#(\d|[a-f]){6}')
        n = p.match(ppd[key])

        return bool(n)
    
def check_ecl(ppd):
    key = 'ecl'
    
    if key not in ppd.keys():
        return False
    else: 
        
        p = re.compile('^((amb)|(blu)|(brn)|(gry)|(grn)|(hzl)|(oth))$')
        n = p.match(ppd[key])

        return bool(n)
    
def check_pid(ppd):
    key = 'pid'
    
    if key not in ppd.keys():
        return False
    else: 
        
        p = re.compile('^\d{9}$')
        n = p.match(ppd[key])

        return bool(n)
    
check_all = [check_byr,check_iyr,check_eyr,check_hgt,check_hcl,check_ecl,check_pid]



In [221]:
n_valid = 0
valid_v = []
for ppd in passport_dicts:
    valid = True
    for check_fun in check_all:
        valid = valid & check_fun(ppd)
    n_valid += valid
    valid_v.append(valid)
print(n_valid)

224


## day 5

In [1]:
import numpy as np

In [4]:
text_file = open('input_05.txt','r')
data = text_file.read()

data_lines = data.split('\n')
data_lines.pop()

''

In [23]:
rows = []
columns = []
seat_id = []

for k,code in enumerate(data_lines):
    row_s = code[0:7]
    column_s = code[7::]
    
    row_s_bin = row_s.replace('F','0').replace('B','1')
    column_s_bin = column_s.replace('L','0').replace('R','1')
    
    row_int = int(row_s_bin,2)
    column_int = int(column_s_bin,2)
    
    rows.append(rows)
    columns.append(column_int)
    seat_id.append(row_int*8+column_int)

In [26]:
answer_1 = np.max(seat_id)
print(answer_1)

806


part 2

In [ ]:
for k in range(answer_1):
    if k+1 in seat_id and 

## day 6

In [1]:
import numpy as np

In [2]:
text_file = open('input_06.txt','r')
data = text_file.read()
groups = data.split('\n\n')

In [13]:
n = 0

for k in groups:
    n+= len(set(k.replace('\n','')))

            
print(n)

6782


part 2

In [14]:
persons = []

for group in groups:
    persons.append(group.split('\n'))

In [21]:
persons[-1].pop()

''

In [29]:
persons_sets = []

for group in persons:
    group_sets = []
    for person in group:
        group_sets.append(set(person))
    persons_sets.append(group_sets)

In [ ]:
n = 0
for ps in persons_sets:
    n += len(set.intersection(*ps))
print(n)

## day 7

In [124]:
import numpy as np
import re
import matplotlib.pyplot as plt

In [3]:
text_file = open('input_07.txt','r')
data = text_file.read()


In [7]:
lines = data.split('\n')
lines.pop()

''

In [16]:
# get all bag colors
bag_colors = []
p = re.compile('[a-z]* [a-z]*')
for line in lines:
    n = p.match(line)
    bag_colors.append(n.group())
    

In [19]:
bag_colors[-1]

'vibrant cyan'

In [21]:
bag_color_dicts ={}

for k,line in enumerate(lines):
    bag_color_dicts[bag_colors[k]] =  []
    
    for bag_color in bag_colors:
        if (bag_color == bag_colors[k])| (bag_color not in line):
            pass
        else:
            bag_color_dicts[bag_colors[k]].append(bag_color)

In [29]:
bag_color_dicts['shiny gold']

['dotted magenta', 'plaid brown', 'clear indigo', 'shiny beige']

In [36]:
n = 0

target = 'shiny gold'
bag_color_target = {}
for bc in bag_color_dicts.keys():
    bag_color_target[bc] = target in bag_color_dicts[bc]

In [45]:
n_before = 0
n = sum(bag_color_target.values())

while n != n_before:
    n_before = n
    for bc,content in bag_color_dicts.items():
        for bag in content:
            if bag_color_target[bag]:
                bag_color_target[bc] = True
    n = sum(bag_color_target.values())
                

In [48]:
print(sum(bag_color_target.values()))

169


part 2

In [57]:
# matrix approach
len(bag_colors)
bag_m = np.zeros((len(bag_colors),len(bag_colors)))

In [66]:
for k,bc_k in enumerate(bag_colors):
    for m, bc_m in enumerate(bag_colors):
        p = re.compile('\d* '+bc_m)
        n = p.search(lines[k])
        
        if n:        
            p2 = re.compile('\d*')
            n2 = p2.match(n.group())

            bag_m[k,m] = int(n2.group())

In [128]:
sgi = bag_colors.index('shiny gold')

In [157]:
mm = np.repeat(np.asmatrix(bag_m[sgi,:]),len(bag_m),axis =0)

In [160]:
a= np.multiply(mm,bag_m)

In [218]:
m_init = np.zeros_like(bag_m)
m_init[sgi,:] = bag_m[sgi,:]

In [222]:
a = range(20)
b = [np.sum(m_init,axis = (0,1))]

m_current = m_init
while np.sum(m_current, axis = (0,1)):
    
    x = np.matmul(m_current,bag_m)
    b.append(np.sum(x,axis = (0,1)))
    m_current = x
    
print(sum(b))

82372.0


test scenario

In [203]:
m_test = np.zeros((7,7))

In [205]:
for k in range(6):
    m_test[k,k+1]=2

In [209]:
m_init_test= np.zeros_like(m_test)

In [210]:
m_init_test[0,:] = m_test[0,:]

In [211]:

b = []

m_current = m_init_test
for k in a:
    
    x = np.matmul(m_current,m_test)
    b.append(np.sum(x,axis = (0,1)))
    m_current = x

In [212]:
b

[4.0,
 8.0,
 16.0,
 32.0,
 64.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0]

In [214]:
sum(b)

124.0

## day 8

In [1]:
import numpy as np
import pandas as pd


In [20]:
data = pd.read_csv('input_08.txt',sep=' ',names = ['instruction','magnitude'])

In [21]:
data['visited'] = False

In [22]:
data.head()

instruction  magnitude  visited
0         acc         -8    False
1         jmp          5    False
2         acc          0    False
3         acc         44    False
4         acc         42    False

In [25]:
data['visited'] = False
accumulator = 0
k = 0
while not data.loc[k,'visited']:
    data.loc[k,'visited'] = True
    if data.loc[k,'instruction'] == 'acc':
        accumulator += data.loc[k,'magnitude']
        k += 1
    elif data.loc[k,'instruction'] == 'jmp':
        k += data.loc[k,'magnitude']
    else:
        k +=1

print(accumulator)

1928


part 2

In [26]:
data.tail()

instruction  magnitude  visited
670         acc         50    False
671         acc         16    False
672         nop       -119    False
673         acc         46    False
674         jmp          1    False

In [ ]:
data['visited'] = False
accumulator = 0
k = 0

In [28]:


data[data['instruction']!= 'acc'].visited.sum()

100

In [31]:
L = (data['instruction']!= 'acc')&(data['visited']==True)

In [47]:
L_indices = np.where(L)[0]

In [60]:
for changed in L_indices:
    data_test = data.copy()
    if data_test.loc[changed,'instruction'] == 'nop':
        data_test.loc[changed, 'instruction'] = 'jmp'
    else:
        data_test.loc[changed, 'instruction'] = 'nop'    
    
    data_test['visited'] = False
    accumulator = 0
    k = 0
    while not data_test.loc[k,'visited']:
        data_test.loc[k,'visited'] = True
        if data_test.loc[k,'instruction'] == 'acc':
            accumulator += data_test.loc[k,'magnitude']
            k += 1
        elif data_test.loc[k,'instruction'] == 'jmp':
            k += data_test.loc[k,'magnitude']
        else:
            k +=1
        if k == len(data_test):
            print(accumulator)
            a = data_test.copy()
            break



1319


In [61]:
a.tail()

instruction  magnitude  visited
670         acc         50     True
671         acc         16     True
672         nop       -119     True
673         acc         46     True
674         jmp          1     True

## day 9

In [1]:
import numpy as np

In [2]:
with open("input_09.txt") as f:
    code = np.loadtxt(f,dtype = 'i')

In [23]:
preamble = code[0:25]

In [34]:

found = False

check_vector = preamble.copy()
k = 25
while not found:
    AA,BB = np.meshgrid(check_vector,check_vector)
    check_array = AA+BB
    check_array = check_array * (np.eye(len(check_vector))*(-1)+1)
    if code[k] not in check_array:
        found = True
        print(code[k])
        inv_number = code[k]
    else:
        k +=1
        check_vector = code[(k-25):k]
    

90433990


part 2

In [47]:
found = False
start_point = 0
csum =0

while not found:
    end_point = start_point + 1 
    csum = 0
    while csum < inv_number:
        csum = code[start_point:end_point].sum()
        
        if csum == inv_number:
            found = True
            print(code[start_point:end_point].min()+code[start_point:end_point].max())

        else:
            end_point += 1
    
    start_point += 1

11691646



## day 10

In [1]:
import numpy as np


In [2]:
with open('input_10.txt') as f:
    data = np.loadtxt(f)

In [6]:
data_sorted = np.sort(data)

In [7]:
data_sorted[0:4]

array([1., 2., 5., 6.])

In [18]:
differences = np.concatenate((data_sorted,np.array([data_sorted[-1]+3])))-np.concatenate((np.array([0]),data_sorted))

In [28]:
def get_differences(data):
    data_sorted = np.sort(data)
    differences = np.concatenate((data_sorted,np.array([data_sorted[-1]+3])))-np.concatenate((np.array([0]),data_sorted))            
    return differences

In [20]:
L_3 = differences ==3
L_1 = differences == 1

answer = L_3.sum()*L_1.sum()
print(answer)

2310


part 2

In [23]:
import matplotlib.pyplot as plt

In [32]:
with open('input_10_test_2.txt') as f:
    data_test_1 = np.loadtxt(f)

In [33]:
differences_test_1 = get_differences(data_test_1)

In [34]:
differences_test_1

array([1., 1., 1., 1., 3., 1., 1., 1., 1., 3., 3., 1., 1., 1., 3., 1., 1.,
       3., 3., 1., 1., 1., 1., 3., 1., 3., 3., 1., 1., 1., 1., 3.])

In [ ]:
4x4
1x3
1x2


In [ ]:
1111
121
13
22
31
112
211


In [35]:
7**4*4*2

19208

In [40]:
L_n = np.all(np.array([1,1,1,1]) == differences_test_1[1:5])

In [44]:
# find maximum sequence of consecutive 1s

for n in range(1,10):
    sequence = np.ones((1,n))
    for k in range(len(differences)-n):
        L_nk = np.all(sequence == differences[k:k+n])
        
        if L_nk:
            print('sequence of %i consecutive 1s found'%(n))
            break

sequence of 1 consecutive 1s found
sequence of 2 consecutive 1s found
sequence of 3 consecutive 1s found
sequence of 4 consecutive 1s found


In [75]:
n_sequences = np.zeros(4)
test_array = differences.copy()
for n in reversed(range(1,5)):
    sequence = np.ones((1,n))
    for k in range(len(test_array)-n):
        L_nk = np.all(sequence == test_array[k:k+n])
        
        if L_nk:
            n_sequences[n-1] += 1
            test_array[k:k+n] = sequence*3
            
            

In [76]:
multipliers = np.array([1,2,4,7])

answer = np.prod (multipliers**n_sequences)
print(answer)

64793042714624.0


## day 11

In [1]:
import numpy as np

In [65]:
with open('input_11.txt','r') as f:
    data = f.read().split('\n')

In [66]:
data.pop()

''

In [67]:
char_data = []

for line in data: 
    char_data.append(list(line))

In [68]:
ca_data = np.char.array(char_data)

In [69]:
def get_n_occupied(data,m,n):
    
    data_x = data.copy()
    data_x[m,n] = '.'
    m_min = max(0,m-1)
    n_min = max(0,n-1)
    m_max = min(data_x.shape[0],m+2)
    n_max = min(data_x.shape[0],n+2)
    
    test_array = data_x[m_min:m_max,n_min:n_max]
    
    L = test_array == '#'
    
    return L.sum()

In [70]:
changed = True

data_old = ca_data.copy()

while changed:
    changed = False
    data_new = data_old.copy()
    for m in range(data_old.shape[0]):
        for n in range(data_old.shape[1]):
            n_occupied = get_n_occupied(data_old,m,n)
            if data_old[m,n] == '.':
                pass
            elif (data_old[m,n] == 'L')&(n_occupied ==0):
                data_new[m,n] = '#'
                changed = True
            elif (data_old[m,n] == '#')&(n_occupied >=4):
                data_new[m,n] = 'L'
                changed = True
    data_old = data_new.copy()
            
print((data_old =='#').sum())

2299


part 2

In [104]:
with open('input_11.txt','r') as f:
    data = f.read().split('\n')

In [105]:
data.pop()

''

In [106]:
char_data = []

for line in data: 
    char_data.append(list(line))
    
ca_data = np.char.array(char_data)

In [107]:
import itertools

In [108]:
def get_n_occupied_2(data,m,n):
    
    data_x = data.copy()
    data_x[m,n] = '.'
    directions = list(itertools.product([-1,0,1],repeat = 2))
    directions.remove((0,0))
    n_occupied =0
    for direction in directions:
        k = 0
        while True:
            k += 1 
            (m_check,n_check) = k*np.array(direction) + np.array((m,n))
            if (min(m_check,n_check) < 0) | (m_check >= data_x.shape[0]) |(n_check >= data_x.shape[1]):
                break
            if data_x[m_check,n_check]=='L':
                break
            if data_x[m_check,n_check]=='#':
                n_occupied += 1
                break
            
    
    return n_occupied

In [109]:
changed = True

data_old = ca_data.copy()

while changed:
    changed = False
    data_new = data_old.copy()
    for m in range(data_old.shape[0]):
        for n in range(data_old.shape[1]):
            n_occupied = get_n_occupied_2(data_old,m,n)
            if data_old[m,n] == '.':
                pass
            elif (data_old[m,n] == 'L')&(n_occupied ==0):
                data_new[m,n] = '#'
                changed = True
            elif (data_old[m,n] == '#')&(n_occupied >=5):
                data_new[m,n] = 'L'
                changed = True
    data_old = data_new.copy()
            
print((data_old =='#').sum())

2047
